In [1]:

import numpy as np
import pandas as pd 
from copy import copy

import os

In [2]:
dataset = pd.read_csv("C:/Users/SAURAV COOL/Downloads/CleanStatements.csv")

In [3]:
# dataset shape

dataset.shape

(1747, 12)

In [4]:
# Clearing the unnecssary space from columns name to futher process

dataset.rename(columns = {'Date      ':'Date','Description                                                        ':'Description','  Category':'Category','  Amount':'Amount','TransactionUserName ':'TransactionUserName', ' TransactionType':'TransactionType',}, inplace = True)

In [5]:
dataset['Category'].value_counts()

                                  606
                  Cafe company    147
                    Video game    125
            E-commerce company    105
                       Company     70
                                 ...
    American singer-songwriter      1
            Production company      1
                  Mobile phone      1
            Capital of the USA      1
        Song by Chris Costanzo      1
Name: Category, Length: 185, dtype: int64

In [6]:
dataset['TransactionUserName']

0              VIBHORE GOYAL
1                JASJIT KAUR
2                JASJIT KAUR
3              VIBHORE GOYAL
4              VIBHORE GOYAL
                ...
1742           VIBHORE GOYAL
1743             JASJIT KAUR
1744           VIBHORE GOYAL
1745           VIBHORE GOYAL
1746           VIBHORE GOYAL
Name: TransactionUserName, Length: 1747, dtype: object

In [7]:
# Count of null values in each column

dataset.isnull().sum()

Date                        0
Description                 0
InternationTransaction      0
Category                    0
Amount                      0
TransactionUserName         0
TransactionType             0
IsoCurrency                 0
Locality                  224
City                      254
State                     284
Country                   215
dtype: int64

In [8]:
dataset.iloc[:,3]

0                             Video game
1                             Occupation
2
3                             Video game
4                             Video game
                      ...
1742                        Cafe company
1743            Department store company
1744
1745
1746    Former President of South Africa
Name: Category, Length: 1747, dtype: object

In [9]:
# Filling NA/NaN values using the forward fill


dataset.fillna(method = 'pad', inplace = True)

In [10]:
dataset

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country
0,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-127.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
1,12-12-2019,CUT AND STYLEGURGAON ...,0.0,Occupation,-499.0,JASJIT KAUR,Domestic,INR,Sector 4,Gurugram,Haryana,India
2,12-12-2019,MUMUSOGURGAON ...,0.0,,-388.0,JASJIT KAUR,Domestic,INR,Sector 49,Gurugram,Haryana,India
3,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-108.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
4,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-50.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
...,...,...,...,...,...,...,...,...,...,...,...,...
1742,07-07-2019,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India
1743,07-07-2019,SHOPPERS STOP LTD GURGAON ...,0.0,Department store company,-1852.0,JASJIT KAUR,Domestic,INR,Heritage City,Gurugram,Haryana,India
1744,11-07-2019,INDIGOGURGAON ...,0.0,,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1745,11-07-2019,INDIGOGURGAON ...,0.0,,-11718.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1746,11-07-2019,TATA INDICOM-DOCOMOMUMBAI ...,0.0,Former President of South Africa,-1297.0,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India

In [11]:
# Replacing space with NaN values

dataset.replace(r'^\s*$', np.nan, regex =True,inplace = True)

In [12]:
dataset

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country
0,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-127.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
1,12-12-2019,CUT AND STYLEGURGAON ...,0.0,Occupation,-499.0,JASJIT KAUR,Domestic,INR,Sector 4,Gurugram,Haryana,India
2,12-12-2019,MUMUSOGURGAON ...,0.0,NaN,-388.0,JASJIT KAUR,Domestic,INR,Sector 49,Gurugram,Haryana,India
3,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-108.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
4,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-50.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
...,...,...,...,...,...,...,...,...,...,...,...,...
1742,07-07-2019,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India
1743,07-07-2019,SHOPPERS STOP LTD GURGAON ...,0.0,Department store company,-1852.0,JASJIT KAUR,Domestic,INR,Heritage City,Gurugram,Haryana,India
1744,11-07-2019,INDIGOGURGAON ...,0.0,NaN,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1745,11-07-2019,INDIGOGURGAON ...,0.0,NaN,-11718.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1746,11-07-2019,TATA INDICOM-DOCOMOMUMBAI ...,0.0,Former President of South Africa,-1297.0,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India

In [13]:
dataset_orig = copy(dataset)

In [14]:
# Finding out the missing row number and storing them in a list

missing = []
for i in range(len(dataset)):
    if(pd.isnull(dataset.iloc[i,3])):
        missing.append(i)
missing

[2,
 11,
 15,
 18,
 19,
 20,
 21,
 24,
 25,
 26,
 27,
 32,
 35,
 40,
 42,
 46,
 47,
 51,
 52,
 54,
 55,
 58,
 59,
 60,
 63,
 65,
 69,
 75,
 76,
 78,
 79,
 81,
 85,
 86,
 89,
 92,
 95,
 107,
 110,
 112,
 114,
 115,
 116,
 118,
 119,
 122,
 123,
 132,
 134,
 137,
 139,
 146,
 149,
 150,
 152,
 153,
 154,
 164,
 165,
 167,
 168,
 170,
 173,
 174,
 175,
 177,
 178,
 179,
 180,
 181,
 186,
 188,
 190,
 191,
 203,
 204,
 214,
 215,
 219,
 224,
 226,
 227,
 228,
 230,
 234,
 235,
 236,
 237,
 238,
 242,
 244,
 246,
 249,
 250,
 251,
 255,
 259,
 260,
 263,
 264,
 265,
 266,
 270,
 273,
 274,
 277,
 278,
 279,
 280,
 281,
 283,
 287,
 292,
 293,
 299,
 306,
 308,
 311,
 313,
 314,
 316,
 317,
 318,
 320,
 323,
 325,
 333,
 335,
 336,
 339,
 340,
 342,
 347,
 351,
 353,
 355,
 357,
 358,
 359,
 360,
 361,
 363,
 364,
 369,
 371,
 374,
 375,
 383,
 384,
 386,
 387,
 388,
 389,
 392,
 394,
 395,
 396,
 400,
 401,
 404,
 408,
 410,
 412,
 413,
 414,
 415,
 416,
 417,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 429,
 430,
 432,
 433,
 434,
 435,
 436,
 440,
 444,
 446,
 447,
 449,
 460,
 474,
 483,
 494,
 497,
 498,
 502,
 503,
 505,
 506,
 508,
 509,
 511,
 515,
 516,
 519,
 522,
 528,
 532,
 533,
 536,
 547,
 561,
 568,
 569,
 571,
 574,
 575,
 579,
 581,
 584,
 593,
 600,
 602,
 604,
 606,
 607,
 609,
 611,
 617,
 618,
 628,
 629,
 630,
 638,
 639,
 640,
 642,
 643,
 648,
 659,
 661,
 664,
 668,
 674,
 675,
 679,
 683,
 688,
 690,
 694,
 697,
 700,
 701,
 702,
 704,
 706,
 708,
 715,
 722,
 727,
 728,
 730,
 736,
 742,
 745,
 757,
 775,
 796,
 797,
 798,
 799,
 804,
 805,
 806,
 811,
 815,
 816,
 820,
 822,
 826,
 828,
 829,
 831,
 832,
 837,
 838,
 839,
 840,
 841,
 843,
 845,
 851,
 852,
 853,
 854,
 858,
 859,
 876,
 877,
 878,
 880,
 886,
 892,
 895,
 899,
 901,
 902,
 904,
 907,
 916,
 917,
 918,
 919,
 921,
 928,
 929,
 934,
 936,
 937,
 951,
 954,
 960,
 963,
 972,
 975,
 980,
 981,
 986,
 990,
 993,
 995,
 996,
 997,
 1004,
 1016,
 1018,
 1019,
 1026,
 1030,
 1035,
 1037,
 1038,
 1040,
 1041,
 1042,
 1045,
 1048,
 1052,
 1054,
 1058,
 1060,
 1061,
 1064,
 1065,
 1067,
 1072,
 1073,
 1074,
 1077,
 1078,
 1079,
 1082,
 1083,
 1084,
 1085,
 1090,
 1091,
 1092,
 1093,
 1094,
 1098,
 1101,
 1103,
 1104,
 1105,
 1106,
 1111,
 1115,
 1116,
 1126,
 1127,
 1146,
 1147,
 1154,
 1157,
 1159,
 1160,
 1162,
 1164,
 1165,
 1168,
 1169,
 1173,
 1174,
 1175,
 1176,
 1178,
 1179,
 1180,
 1181,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1193,
 1194,
 1196,
 1197,
 1199,
 1200,
 1202,
 1203,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1216,
 1229,
 1232,
 1238,
 1239,
 1240,
 1242,
 1243,
 1245,
 1246,
 1251,
 1253,
 1257,
 1258,
 1259,
 1260,
 1263,
 1264,
 1269,
 1272,
 1275,
 1278,
 1282,
 1283,
 1284,
 1286,
 1288,
 1289,
 1293,
 1295,
 1296,
 1298,
 1300,
 1306,
 1307,
 1308,
 1309,
 1317,
 1320,
 1322,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1334,
 1335,
 1338,
 1340,
 1341,
 1342,
 1344,
 1345,
 1346,
 1347,
 1349,
 1351,
 1352,
 1353,
 1357,
 1360,
 1364,
 1365,
 1368,
 1369,
 1370,
 1374,
 1375,
 1377,
 1378,
 1379,
 1380,
 1382,
 1383,
 1384,
 1385,
 1392,
 1394,
 1396,
 1400,
 1401,
 1402,
 1404,
 1409,
 1411,
 1414,
 1415,
 1417,
 1418,
 1420,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1432,
 1433,
 1434,
 1437,
 1438,
 1440,
 1444,
 1463,
 1465,
 1466,
 1475,
 1484,
 1493,
 1495,
 1514,
 1515,
 1518,
 1521,
 1529,
 1531,
 1535,
 1538,
 1546,
 1552,
 1569,
 1575,
 1577,
 1579,
 1583,
 1584,
 1585,
 1586,
 1590,
 1593,
 1594,
 1597,
 1600,
 1601,
 1603,
 1611,
 1612,
 1614,
 1615,
 1631,
 1632,
 1633,
 1634,
 1635,
 1638,
 1642,
 1643,
 1645,
 1646,
 1649,
 1650,
 1651,
 1652,
 1653,
 1655,
 1660,
 1661,
 1663,
 1664,
 1665,
 1667,
 1668,
 1672,
 1673,
 1677,
 1679,
 1681,
 1682,
 1693,
 1696,
 1698,
 1699,
 1708,
 1712,
 1724,
 1725,
 1732,
 1736,
 1744,
 1745]

In [15]:
# Droping of Category column

X = dataset.drop(['Category'],axis = 1)

In [16]:
# Finding the columns with categorical valriable 

cols = X.columns

num_cols = dataset._get_numeric_data().columns
catcols = list(set(cols) - set(num_cols))
print(catcols)

['IsoCurrency', 'Locality', 'Date', 'TransactionType', 'Description', 'TransactionUserName', 'State', 'City', 'Country']

In [17]:
# Converting categoriacal data into numerical data

from sklearn.preprocessing import LabelEncoder
for c in catcols :
    LE = LabelEncoder() 
    dataset[c] = LE.fit_transform(dataset[c])

In [18]:
dataset = dataset.drop(['InternationTransaction','Locality','Date'],axis = 1)

In [19]:
missing

[2,
 11,
 15,
 18,
 19,
 20,
 21,
 24,
 25,
 26,
 27,
 32,
 35,
 40,
 42,
 46,
 47,
 51,
 52,
 54,
 55,
 58,
 59,
 60,
 63,
 65,
 69,
 75,
 76,
 78,
 79,
 81,
 85,
 86,
 89,
 92,
 95,
 107,
 110,
 112,
 114,
 115,
 116,
 118,
 119,
 122,
 123,
 132,
 134,
 137,
 139,
 146,
 149,
 150,
 152,
 153,
 154,
 164,
 165,
 167,
 168,
 170,
 173,
 174,
 175,
 177,
 178,
 179,
 180,
 181,
 186,
 188,
 190,
 191,
 203,
 204,
 214,
 215,
 219,
 224,
 226,
 227,
 228,
 230,
 234,
 235,
 236,
 237,
 238,
 242,
 244,
 246,
 249,
 250,
 251,
 255,
 259,
 260,
 263,
 264,
 265,
 266,
 270,
 273,
 274,
 277,
 278,
 279,
 280,
 281,
 283,
 287,
 292,
 293,
 299,
 306,
 308,
 311,
 313,
 314,
 316,
 317,
 318,
 320,
 323,
 325,
 333,
 335,
 336,
 339,
 340,
 342,
 347,
 351,
 353,
 355,
 357,
 358,
 359,
 360,
 361,
 363,
 364,
 369,
 371,
 374,
 375,
 383,
 384,
 386,
 387,
 388,
 389,
 392,
 394,
 395,
 396,
 400,
 401,
 404,
 408,
 410,
 412,
 413,
 414,
 415,
 416,
 417,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 429,
 430,
 432,
 433,
 434,
 435,
 436,
 440,
 444,
 446,
 447,
 449,
 460,
 474,
 483,
 494,
 497,
 498,
 502,
 503,
 505,
 506,
 508,
 509,
 511,
 515,
 516,
 519,
 522,
 528,
 532,
 533,
 536,
 547,
 561,
 568,
 569,
 571,
 574,
 575,
 579,
 581,
 584,
 593,
 600,
 602,
 604,
 606,
 607,
 609,
 611,
 617,
 618,
 628,
 629,
 630,
 638,
 639,
 640,
 642,
 643,
 648,
 659,
 661,
 664,
 668,
 674,
 675,
 679,
 683,
 688,
 690,
 694,
 697,
 700,
 701,
 702,
 704,
 706,
 708,
 715,
 722,
 727,
 728,
 730,
 736,
 742,
 745,
 757,
 775,
 796,
 797,
 798,
 799,
 804,
 805,
 806,
 811,
 815,
 816,
 820,
 822,
 826,
 828,
 829,
 831,
 832,
 837,
 838,
 839,
 840,
 841,
 843,
 845,
 851,
 852,
 853,
 854,
 858,
 859,
 876,
 877,
 878,
 880,
 886,
 892,
 895,
 899,
 901,
 902,
 904,
 907,
 916,
 917,
 918,
 919,
 921,
 928,
 929,
 934,
 936,
 937,
 951,
 954,
 960,
 963,
 972,
 975,
 980,
 981,
 986,
 990,
 993,
 995,
 996,
 997,
 1004,
 1016,
 1018,
 1019,
 1026,
 1030,
 1035,
 1037,
 1038,
 1040,
 1041,
 1042,
 1045,
 1048,
 1052,
 1054,
 1058,
 1060,
 1061,
 1064,
 1065,
 1067,
 1072,
 1073,
 1074,
 1077,
 1078,
 1079,
 1082,
 1083,
 1084,
 1085,
 1090,
 1091,
 1092,
 1093,
 1094,
 1098,
 1101,
 1103,
 1104,
 1105,
 1106,
 1111,
 1115,
 1116,
 1126,
 1127,
 1146,
 1147,
 1154,
 1157,
 1159,
 1160,
 1162,
 1164,
 1165,
 1168,
 1169,
 1173,
 1174,
 1175,
 1176,
 1178,
 1179,
 1180,
 1181,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1193,
 1194,
 1196,
 1197,
 1199,
 1200,
 1202,
 1203,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1216,
 1229,
 1232,
 1238,
 1239,
 1240,
 1242,
 1243,
 1245,
 1246,
 1251,
 1253,
 1257,
 1258,
 1259,
 1260,
 1263,
 1264,
 1269,
 1272,
 1275,
 1278,
 1282,
 1283,
 1284,
 1286,
 1288,
 1289,
 1293,
 1295,
 1296,
 1298,
 1300,
 1306,
 1307,
 1308,
 1309,
 1317,
 1320,
 1322,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1334,
 1335,
 1338,
 1340,
 1341,
 1342,
 1344,
 1345,
 1346,
 1347,
 1349,
 1351,
 1352,
 1353,
 1357,
 1360,
 1364,
 1365,
 1368,
 1369,
 1370,
 1374,
 1375,
 1377,
 1378,
 1379,
 1380,
 1382,
 1383,
 1384,
 1385,
 1392,
 1394,
 1396,
 1400,
 1401,
 1402,
 1404,
 1409,
 1411,
 1414,
 1415,
 1417,
 1418,
 1420,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1432,
 1433,
 1434,
 1437,
 1438,
 1440,
 1444,
 1463,
 1465,
 1466,
 1475,
 1484,
 1493,
 1495,
 1514,
 1515,
 1518,
 1521,
 1529,
 1531,
 1535,
 1538,
 1546,
 1552,
 1569,
 1575,
 1577,
 1579,
 1583,
 1584,
 1585,
 1586,
 1590,
 1593,
 1594,
 1597,
 1600,
 1601,
 1603,
 1611,
 1612,
 1614,
 1615,
 1631,
 1632,
 1633,
 1634,
 1635,
 1638,
 1642,
 1643,
 1645,
 1646,
 1649,
 1650,
 1651,
 1652,
 1653,
 1655,
 1660,
 1661,
 1663,
 1664,
 1665,
 1667,
 1668,
 1672,
 1673,
 1677,
 1679,
 1681,
 1682,
 1693,
 1696,
 1698,
 1699,
 1708,
 1712,
 1724,
 1725,
 1732,
 1736,
 1744,
 1745]

In [20]:
# Preparing test data set

X_test = dataset[dataset['Category'].isnull()]
X_test = X_test.drop(['Category'],axis = 1)

In [21]:
X_train = dataset.dropna(subset = ['Category'])

In [22]:
# implementing label encoder to y_train having no NaN values

y_train = X_train['Category']
y_train = LE.fit_transform(y_train)

In [23]:
X_train = X_train.drop(['Category'],axis = 1)

In [24]:
for i in range(len(missing)):
    print(missing[i])

2
11
15
18
19
20
21
24
25
26
27
32
35
40
42
46
47
51
52
54
55
58
59
60
63
65
69
75
76
78
79
81
85
86
89
92
95
107
110
112
114
115
116
118
119
122
123
132
134
137
139
146
149
150
152
153
154
164
165
167
168
170
173
174
175
177
178
179
180
181
186
188
190
191
203
204
214
215
219
224
226
227
228
230
234
235
236
237
238
242
244
246
249
250
251
255
259
260
263
264
265
266
270
273
274
277
278
279
280
281
283
287
292
293
299
306
308
311
313
314
316
317
318
320
323
325
333
335
336
339
340
342
347
351
353
355
357
358
359
360
361
363
364
369
371
374
375
383
384
386
387
388
389
392
394
395
396
400
401
404
408
410
412
413
414
415
416
417
421
422
423
424
425
426
427
429
430
432
433
434
435
436
440
444
446
447
449
460
474
483
494
497
498
502
503
505
506
508
509
511
515
516
519
522
528
532
533
536
547
561
568
569
571
574
575
579
581
584
593
600
602
604
606
607
609
611
617
618
628
629
630
638
639
640
642
643
648
659
661
664
668
674
675
679
683
688
690
694
697
700
701
702
704
706
708
715
722
727
728
730
736
742
745
757
775
796
797
798
799
804
805
806
811
815
816
820
822
826
828
829
831
832
837
838
839
840
841
843
845
851
852
853
854
858
859
876
877
878
880
886
892
895
899
901
902
904
907
916
917
918
919
921
928
929
934
936
937
951
954
960
963
972
975
980
981
986
990
993
995
996
997
1004
1016
1018
1019
1026
1030
1035
1037
1038
1040
1041
1042
1045
1048
1052
1054
1058
1060
1061
1064
1065
1067
1072
1073
1074
1077
1078
1079
1082
1083
1084
1085
1090
1091
1092
1093
1094
1098
1101
1103
1104
1105
1106
1111
1115
1116
1126
1127
1146
1147
1154
1157
1159
1160
1162
1164
1165
1168
1169
1173
1174
1175
1176
1178
1179
1180
1181
1183
1184
1185
1186
1187
1188
1193
1194
1196
1197
1199
1200
1202
1203
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1216
1229
1232
1238
1239
1240
1242
1243
1245
1246
1251
1253
1257
1258
1259
1260
1263
1264
1269
1272
1275
1278
1282
1283
1284
1286
1288
1289
1293
1295
1296
1298
1300
1306
1307
1308
1309
1317
1320
1322
1326
1327
1328
1329
1330
1331
1334
1335
1338
1340
1341
1342
1344
1345
1346
1347
1349
1351
1352
1353
1357
1360
1364
1365
1368
1369
1370
1374
1375
1377
1378
1379
1380
1382
1383
1384
1385
1392
1394
1396
1400
1401
1402
1404
1409
1411
1414
1415
1417
1418
1420
1422
1423
1424
1425
1426
1427
1428
1429
1430
1432
1433
1434
1437
1438
1440
1444
1463
1465
1466
1475
1484
1493
1495
1514
1515
1518
1521
1529
1531
1535
1538
1546
1552
1569
1575
1577
1579
1583
1584
1585
1586
1590
1593
1594
1597
1600
1601
1603
1611
1612
1614
1615
1631
1632
1633
1634
1635
1638
1642
1643
1645
1646
1649
1650
1651
1652
1653
1655
1660
1661
1663
1664
1665
1667
1668
1672
1673
1677
1679
1681
1682
1693
1696
1698
1699
1708
1712
1724
1725
1732
1736
1744
1745

In [25]:
X_train

,Description,Amount,TransactionUserName,TransactionType,IsoCurrency,City,State,Country
0,559,-127.0,2,0,0,19,4,0
1,108,-499.0,1,0,0,19,4,0
3,559,-108.0,2,0,0,19,4,0
4,559,-50.0,2,0,0,19,4,0
5,428,-2000.0,2,0,0,36,16,0
...,...,...,...,...,...,...,...,...
1740,290,-120.0,2,0,0,19,4,0
1741,517,-1798.0,2,0,0,19,4,0
1742,73,-298.0,2,0,0,19,4,0
1743,501,-1852.0,1,0,0,19,4,0
1746,543,-1297.0,2,0,0,32,6,0

In [26]:
# Using Random forest algorithm to the predict the remaining category column cells

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 200)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [27]:
# converting numerical data to categorical data
y_pred2 = LE.inverse_transform(y_pred)

In [28]:
dataset_orig

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country
0,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-127.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
1,12-12-2019,CUT AND STYLEGURGAON ...,0.0,Occupation,-499.0,JASJIT KAUR,Domestic,INR,Sector 4,Gurugram,Haryana,India
2,12-12-2019,MUMUSOGURGAON ...,0.0,NaN,-388.0,JASJIT KAUR,Domestic,INR,Sector 49,Gurugram,Haryana,India
3,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-108.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
4,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-50.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
...,...,...,...,...,...,...,...,...,...,...,...,...
1742,07-07-2019,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India
1743,07-07-2019,SHOPPERS STOP LTD GURGAON ...,0.0,Department store company,-1852.0,JASJIT KAUR,Domestic,INR,Heritage City,Gurugram,Haryana,India
1744,11-07-2019,INDIGOGURGAON ...,0.0,NaN,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1745,11-07-2019,INDIGOGURGAON ...,0.0,NaN,-11718.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1746,11-07-2019,TATA INDICOM-DOCOMOMUMBAI ...,0.0,Former President of South Africa,-1297.0,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India

In [29]:
# Predicted values for the cells of category column which have (remained blank or with Space)

y_pred2

array(['                 Radio station', '                     2017 film',
       '             Indian film actor', '                     Nightclub',
       '                   Hotel chain', '                   Hotel chain',
       '                   Hotel chain', '          Novel by Tamsyn Muir',
       '          Novel by Tamsyn Muir', '                       Company',
       '              Chemical element', '           Coffeehouse company',
       '  Fast food restaurant company',
       'Multinational conglomerate company',
       '          Novel by Tamsyn Muir', '                     2015 film',
       '          Novel by Tamsyn Muir', '             Chemical compound',
       '             Chemical compound', '            E-commerce company',
       '                    Video game', '            E-commerce company',
       '          Novel by Tamsyn Muir', '   American television program',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                    Video game', '                       Company',
       '                    Video game', '                 Song by Queen',
       '            Book by Eric Carle', '                    Video game',
       '                Retail company', '                American actor',
       '                     Dog breed', '                    Video game',
       '                    Video game', '            E-commerce company',
       '          Novel by Tamsyn Muir', '              Poem by Tulsidas',
       '            E-commerce company', '            E-commerce company',
       '            E-commerce company', '                     2001 film',
       '            E-commerce company', '            E-commerce company',
       '          Novel by Tamsyn Muir', '            E-commerce company',
       '           Coffeehouse company', '              American actress',
       '                     2001 film', '          Novel by Tamsyn Muir',
       '                  Cafe company', '                  Cafe company',
       '                    Politician', '                         Event',
       '                       Company', '                 Song by Queen',
       '                    Video game', '                         Event',
       '                    Video game', '              American actress',
       '                Retail company', '          Novel by Tamsyn Muir',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                    Video game', '            Capital of the USA',
       '                         Event', '          Novel by Tamsyn Muir',
       '                     2015 film', '       Clothing retail company',
       '             Indian researcher', 'City in the island of Montreal',
       '                       Company', '          Novel by Tamsyn Muir',
       '       Clothing retail company', '                     2015 film',
       '                    Occupation', '           Architectural style',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '                       Company', '               Political party',
       '                       Company', '                    Video game',
       '                    Video game', '                    Video game',
       '            Restaurant company', '          Novel by Tamsyn Muir',
       '           Song by Drew Seeley', '    Telecommunications company',
       '               Indian language', '                Retail company',
       '                    Video game', '                    Video game',
       '   Board of education in India', '                 City in India',
       '                  Cafe company', '            E-commerce company',
       '                    Video game', '                    Video game',
       '                       Company', '                       Company',
       '                  Mobile phone', '          Novel by Tamsyn Muir',
       '          Novel by Jane Austen', '                       Company',
       '                  Mobile phone', '                 City in India',
       '   Board of education in India', '                        Plants',
       '            City in California', '                       Company',
       '                    Video game', '          Novel by Tamsyn Muir',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                       Company', '                Italian region',
       '          Novel by Tamsyn Muir', '            E-commerce company',
       '            E-commerce company', '                       Company',
       '          Novel by Tamsyn Muir', '         International airline',
       '                       Company', '                    Politician',
       '                Italian region', '                Retail company',
       '                     2015 film', '   American television program',
       '                    Medication', '                       Company',
       '        Indian playback singer', '                     2001 film',
       '    Electronics retail company', '                    Video game',
       '            E-commerce company', '            E-commerce company',
       '                         Event', '               Fashion company',
       '                     2014 film', '             Fast food company',
       '  Fast food restaurant company', '             Fast food company',
       '            E-commerce company', '    Electronics retail company',
       '                Retail company', '                       Company',
       '                       Company', '                       Company',
       '                Retail company', '                  Private club',
       '             Chemical compound', '                Retail company',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '                       Company', '                       Company',
       '          Novel by Tamsyn Muir', '                Field of study',
       '    Telecommunications company', '                    Occupation',
       '          Novel by Tamsyn Muir', '               Railway company',
       '               Railway company', '               Railway company',
       '               Railway company', '            Book by Eric Carle',
       '                    Occupation', '               Railway company',
       '          Novel by Tamsyn Muir', '                    Occupation',
       '          Novel by Tamsyn Muir', '                         Event',
       '                    Politician', '           Hospitality company',
       '          Novel by Tamsyn Muir', '            Restaurant company',
       '          Novel by Tamsyn Muir', '           Coffeehouse company',
       '           Coffeehouse company', '                    Video game',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                    Video game', '  Online food ordering company',
       '             Fast food company', '               Political party',
       '                   Corporation', '   American television program',
       '                    Video game', '                    Politician',
       '                    Video game', '          Novel by Tamsyn Muir',
       '               Massif in Nepal', '                    Legislator',
       '                  Song by 4Joy', '          Novel by Tamsyn Muir',
       '                       Company', '           Song by Drew Seeley',
       '            E-commerce company', '         Book by Alan Beaulieu',
       '             Fast food company', '                Italian region',
       '                   Corporation', '          Novel by Tamsyn Muir',
       '                     2001 film', '               Political party',
       '      Department store company', '            E-commerce company',
       '            E-commerce company', '          Novel by Tamsyn Muir',
       '            Technology company', '                       Company',
       '                     2001 film', '   American television program',
       '                    Video game', '                     2015 film',
       '   American television program', '                       Company',
       '                       Company', '   American television program',
       '                 Radio station', '                    Video game',
       '                       Company', '                   Corporation',
       '                Field of study', '                 Song by Queen',
       '    Telecommunications company', '                    Occupation',
       '                Indian actress', '                Indian actress',
       '            E-commerce company', '           Hypermarket company',
       '           Coffeehouse company', '           Hypermarket company',
       '                   Corporation', '                  Cafe company',
       '                       Company', '                   Hotel chain',
       '                  Song by Rhye', '                 City in Spain',
       '                    Politician', '       Clothing retail company',
       '        Hardware store company', '    Telecommunications company',
       '                        Agency', '                  Cafe company',
       '    Telecommunications company', '   American television program',
       '                 Song by Queen', '                    Video game',
       '              City in New York', '                 Radio station',
       '                    Video game', '                    Video game',
       '                         Event', '                 City in India',
       '               American sitcom', '   American television program',
       '  Fast food restaurant company', '                       Company',
       '                 Song by Queen', '                       Company',
       '                   Corporation', '                    Video game',
       '                Retail company', '                Cinema company',
       '                       Company', '                 Radio station',
       '                       Company', '                    Video game',
       '                  Song by Rhye', '           Song by Drew Seeley',
       '              Chemical element', '            E-commerce company',
       '                    Video game', '                 Radio station',
       '                    Video game', '   American television program',
       '                Indian actress', '                Retail company',
       '                       Company', '      Department store company',
       '                Indian actress', '                Retail company',
       '                 Radio station', '                    Politician',
       '                    Politician', '                 Radio station',
       '                    Video game', '               American sitcom',
       '      Department store company', '                 Radio station',
       '                Indian actress', '                    Politician',
       '                    Video game', '       Clothing retail company',
       '                  Cafe company', '                   Corporation',
       '                Indian actress', '                    Video game',
       '               American sitcom', '                    Politician',
       '          Novel by Tamsyn Muir', '             Indian researcher',
       '             Indian researcher', '          Novel by Tamsyn Muir',
       '                 Song by Queen', '    Telecommunications company',
       '           Coffeehouse company', '            Restaurant company',
       '            City in California', '                       Company',
       '          Novel by Tamsyn Muir', '                       Company',
       '                  Song by Rhye', '          Novel by Tamsyn Muir',
       '          Novel by Tamsyn Muir', '  Fast food restaurant company',
       '  Fast food restaurant company', '  Online food ordering company',
       '                Retail company', '                Italian region',
       '                    Video game', '                    Video game',
       '            Restaurant company', '                Field of study',
       '          Novel by Tamsyn Muir', '    Telecommunications company',
       '         Book by Alan Beaulieu', '                    Video game',
       '   Board of education in India', '   American television program',
       '            E-commerce company', '                    Video game',
       '          Novel by Tamsyn Muir', '                    Video game',
       '            Restaurant company', '                   Corporation',
       '            Restaurant company', '                    Video game',
       '                    Video game', '                    Video game',
       '          Novel by Tamsyn Muir', '            Restaurant company',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                Field of study', '            E-commerce company',
       '            E-commerce company', '          Novel by Tamsyn Muir',
       '                    Video game', '                    Video game',
       '                 Radio station', '                       Company',
       '          Novel by Tamsyn Muir', '                Field of study',
       '            Book by Eric Carle', '          Novel by Tamsyn Muir',
       '          Novel by Tamsyn Muir', '          Novel by Tamsyn Muir',
       '                       Company', '                  Song by 4Joy',
       '                Field of study', '            E-commerce company',
       '            E-commerce company', '          Novel by Tamsyn Muir',
       '                       Company', '          Novel by Tamsyn Muir',
       '                Indian actress', '                Cinema company',
       '           Coffeehouse company', '                       Company',
       '            E-commerce company', '            E-commerce company',
       '            City in California', '       Clothing retail company',
       '                Italian region', '                     1988 film',
       '                       Company', '                       Company',
       '                    Video game', '            Restaurant company',
       '            Restaurant company', '                    Video game',
       '                    Video game', '          Novel by Tamsyn Muir',
       '                 City in India', '                       Company',
       '                    Video game', '          Novel by Tamsyn Muir',
       '                    Video game', '                    Video game',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                    Video game', '                    Video game',
       '                       Company', '                 City in India',
       '                       Company', '            Restaurant company',
       '            Restaurant company', '                    Video game',
       '              City in New York', '          Novel by Tamsyn Muir',
       '                 City in Spain', '                Indian actress',
       '                       Company', '          Novel by Tamsyn Muir',
       '            E-commerce company', '    Electronics retail company',
       '                 City in India', '                  Cafe company',
       '                    Video game', '                  Cafe company',
       '                        Animal', '                  Cafe company',
       '                       Company', '  Fast food restaurant company',
       '                    Video game', '                    Video game',
       '                 City in Spain', '                    Video game',
       '          Novel by Tamsyn Muir', '          Novel by Tamsyn Muir',
       '            Television channel', '                       Company',
       '           Coffeehouse company', '            E-commerce company',
       '          Novel by Tamsyn Muir', '                    Video game',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                    Video game', '                    Video game',
       '                    Video game', '          Novel by Tamsyn Muir',
       '                     1984 film', '            City in California',
       '      Department store company', '          Novel by Tamsyn Muir',
       '                    Video game', '                    Video game',
       '                    Video game', '                  Cafe company',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                    Video game', '                    Video game',
       '               Broadcast genre', '          Novel by Tamsyn Muir',
       '                    Video game', '          Novel by Tamsyn Muir',
       '                    Video game', '                    Video game',
       '          Novel by Tamsyn Muir', '          Novel by Tamsyn Muir',
       '                    Video game', '                    Video game',
       '          Novel by Tamsyn Muir', '                    Video game',
       '                Retail company', '                       Airline',
       '                    Video game', '                 Song by Queen',
       '                    Video game', '                       Company',
       '          Broadcasting service', '          Novel by Tamsyn Muir',
       '            E-commerce company', '                       Airline',
       '            Indian businessman', '  Fast food restaurant company',
       '                    Video game', '                    Video game',
       '          Novel by Tamsyn Muir', '                       Company',
       '  Online food ordering company', '               Political party',
       '               American sitcom', '                     Dog breed',
       '            E-commerce company', '                       Company',
       '                       Company', '             Fast food company',
       '  Fast food restaurant company', '                Field of study',
       '        Hardware store company', '               American sitcom',
       '                 Radio station', '                       Company',
       '             Fast food company', '              American actress',
       '             Automotive marque', '                    Politician',
       '                       Company', '                       Company',
       '        Hardware store company', '                  Cafe company',
       '             Automotive marque', '              American actress',
       '             Automotive marque', '             Automotive marque',
       '              American actress', '              American actress',
       '              American actress', '              American actress',
       '            E-commerce company', '                       Company',
       '      Furniture retail company', '                Field of study',
       '  Fast food restaurant company', '                       Company',
       '            Television channel', '                     2014 film',
       '                 Song by Queen', '               Political party',

In [30]:
# Fillin g back the predicted value to the original dataset

for i in range(len(missing)):
    dataset_orig.iloc[missing[i],3] = y_pred2[i]

In [31]:
dataset_orig

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country
0,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-127.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
1,12-12-2019,CUT AND STYLEGURGAON ...,0.0,Occupation,-499.0,JASJIT KAUR,Domestic,INR,Sector 4,Gurugram,Haryana,India
2,12-12-2019,MUMUSOGURGAON ...,0.0,Radio station,-388.0,JASJIT KAUR,Domestic,INR,Sector 49,Gurugram,Haryana,India
3,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-108.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
4,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-50.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India
...,...,...,...,...,...,...,...,...,...,...,...,...
1742,07-07-2019,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India
1743,07-07-2019,SHOPPERS STOP LTD GURGAON ...,0.0,Department store company,-1852.0,JASJIT KAUR,Domestic,INR,Heritage City,Gurugram,Haryana,India
1744,11-07-2019,INDIGOGURGAON ...,0.0,Restaurant company,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1745,11-07-2019,INDIGOGURGAON ...,0.0,City in California,-11718.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India
1746,11-07-2019,TATA INDICOM-DOCOMOMUMBAI ...,0.0,Former President of South Africa,-1297.0,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India

In [32]:
# Converting dataset_orig(havving all cells including empty of blank cell in categories) to .csv

dataset_orig.to_csv("result_final.csv")

In [33]:
dataset_orig['tags']= ['food' for i in range(1747)]

In [34]:
dataset_orig

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country,tags
0,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-127.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India,food
1,12-12-2019,CUT AND STYLEGURGAON ...,0.0,Occupation,-499.0,JASJIT KAUR,Domestic,INR,Sector 4,Gurugram,Haryana,India,food
2,12-12-2019,MUMUSOGURGAON ...,0.0,Radio station,-388.0,JASJIT KAUR,Domestic,INR,Sector 49,Gurugram,Haryana,India,food
3,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-108.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India,food
4,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-50.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India,food
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1742,07-07-2019,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,food
1743,07-07-2019,SHOPPERS STOP LTD GURGAON ...,0.0,Department store company,-1852.0,JASJIT KAUR,Domestic,INR,Heritage City,Gurugram,Haryana,India,food
1744,11-07-2019,INDIGOGURGAON ...,0.0,Restaurant company,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India,food
1745,11-07-2019,INDIGOGURGAON ...,0.0,City in California,-11718.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India,food
1746,11-07-2019,TATA INDICOM-DOCOMOMUMBAI ...,0.0,Former President of South Africa,-1297.0,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India,food

In [35]:
tag_list = []

Food = ['Cafe', 'CAFE', 'COFFE','RESTAURANT','restaurant','Fast food', 'FOODS','Massif','SWEETS','HALDIRAM','SUBWAY','BARISTA','KHANNA','EVENT','Dish','Restaurant', 'BURGER','STARBUCKS','DOMINOS','LAKSHITA','BREWER','SANWARIA','WOW MOMO','PLAZA','UBER']
Hospitality = ['Hotel','Hotelchain','SMARTBUY','Event','Hospitality','party','WINE','NAMITIYA','APOLLO','LOUNGE','LEELA','LOUNGE']
Travel = ['SPACEJAIPUR','OLACABS','Airline','CLEARTRIP','airline','Railway']
Entertainment = ['Video game','Radio station', 'TOM','film','Cinema','FILMS','Novel','Theatre','Sports club','Oceanic','footballer','Song','PVR','BOOK MY SHOW','Television','Guerrilla war'] 
Shopping = ['E-commerce','Electronics','Chemical','CHEMIST','FRESH ZONE','PAYTM','PHARMACY','MART','Retail','STORE','ORIENT','TRADIN','Insurance','retail','store','Store','IGST','Myntra','NAMKEEN','Salon','ARCHIES','CLINIC','LIFE STYLE','FUELS','PETRO','NETBANKING','Telecommunications','PAYMENTS','IOCL','MEDICA','BILL DESK','SALON','GODADDY','BPCL','VIDYUT','RETAIL','TATA','marketing']

In [36]:
# Tagging each row with particular category from('Food','Hospitality','Travel', 'Entertainment','Shopping','Other') by contcatenating their Description and Category and using the keywods from them 

for i in range(dataset_orig.shape[0]):
    
    # concatenating the Description and Category
    a = dataset_orig.iloc[i]['Description'] + dataset_orig.iloc[i]['Category']
    
    # converting all the elements in a to lowercase
    
    a = (' '.join(a.lower().strip().split()))
    for x in Food:
        if(x.lower() in a):
            tag_list.append("Food")
            break
    if(len(tag_list)<i+1):
       
        for x in Shopping:
            if(x.lower() in a):
                tag_list.append("Shopping")
                break

    if (len(tag_list)<i+1) :
        
        for x in Hospitality:
            if(x.lower() in a):
                tag_list.append("Hospitality")
                break
    if(len(tag_list)<i+1):
        
        for x in Travel:
            if(x.lower() in a):
                tag_list.append("Travel")
                break
    if(len(tag_list)<i+1):
       
        for x in Entertainment:
            if(x.lower() in a):
                tag_list.append("Entertainment")
                break
    if(len(tag_list)<i+1):
        tag_list.append("others")

In [37]:
len(tag_list)

1747

In [38]:
# Updating the data of tags coulmn by replacing them from tag_list elements 

dataset_orig['tags']= tag_list

In [39]:
dataset_orig

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country,tags
0,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-127.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India,Entertainment
1,12-12-2019,CUT AND STYLEGURGAON ...,0.0,Occupation,-499.0,JASJIT KAUR,Domestic,INR,Sector 4,Gurugram,Haryana,India,others
2,12-12-2019,MUMUSOGURGAON ...,0.0,Radio station,-388.0,JASJIT KAUR,Domestic,INR,Sector 49,Gurugram,Haryana,India,Entertainment
3,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-108.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India,Entertainment
4,12-12-2019,THE ROOM GURGAON ...,0.0,Video game,-50.0,VIBHORE GOYAL,Domestic,INR,Central Park II,Gurugram,Haryana,India,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1742,07-07-2019,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
1743,07-07-2019,SHOPPERS STOP LTD GURGAON ...,0.0,Department store company,-1852.0,JASJIT KAUR,Domestic,INR,Heritage City,Gurugram,Haryana,India,Shopping
1744,11-07-2019,INDIGOGURGAON ...,0.0,Restaurant company,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India,Food
1745,11-07-2019,INDIGOGURGAON ...,0.0,City in California,-11718.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India,others
1746,11-07-2019,TATA INDICOM-DOCOMOMUMBAI ...,0.0,Former President of South Africa,-1297.0,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India,Shopping

In [40]:
from datetime import datetime
dataset_orig['Date'] = pd.to_datetime(dataset_orig['Date'])

In [41]:
dataset_orig.to_csv("tag.csv")

In [42]:
M = pd.unique(dataset_orig['TransactionUserName'])

In [43]:
M

array(['       VIBHORE GOYAL', '         JASJIT KAUR',
       '          INDU GOYAL'], dtype=object)

In [44]:
dataset_orig.columns

Index(['Date', 'Description', 'InternationTransaction', 'Category', 'Amount',
       'TransactionUserName', 'TransactionType', 'IsoCurrency', 'Locality',
       'City', 'State', 'Country', 'tags'],
      dtype='object')

In [45]:
M

array(['       VIBHORE GOYAL', '         JASJIT KAUR',
       '          INDU GOYAL'], dtype=object)

In [46]:
N = pd.unique(dataset_orig['tags'])

In [47]:
# Customized meta tags for categories each row

In [48]:
N

array(['Entertainment', 'others', 'Shopping', 'Travel', 'Food',
       'Hospitality'], dtype=object)

In [49]:
# Fetching data with following conditions from dataset_orig including metatags for each rows

dataset_orig.loc[(dataset_orig['TransactionUserName'] == '       VIBHORE GOYAL') & (dataset_orig['tags'] == 'Food')]

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country,tags
32,2019-12-19,SMARTBUY BANGALORE ...,0.0,Coffeehouse company,-7027.0,VIBHORE GOYAL,Domestic,INR,DLF Colony,Gurugram,Haryana,India,Food
134,2020-11-01,SMARTBUYBANGALORE ...,0.0,Coffeehouse company,-6978.0,VIBHORE GOYAL,Domestic,INR,Sector 4,Gurugram,Haryana,India,Food
198,2019-01-02,KFC SEC 47 SOHNA ROAD GGURGAON ...,0.0,Fast food restaurant company,-265.0,VIBHORE GOYAL,Domestic,INR,D1 Block,Gurugram,Haryana,India,Food
207,2019-02-02,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-147.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
253,2020-01-16,UBER GURGAON ...,0.0,Online food ordering company,-1.0,VIBHORE GOYAL,Domestic,INR,Acharya Puri Extension,Gurugram,Haryana,India,Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1734,2019-05-07,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-292.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
1739,2019-06-07,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-725.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
1740,2019-06-07,KFC SEC 47 SOHNA ROAD GGURGAON ...,0.0,Fast food restaurant company,-120.0,VIBHORE GOYAL,Domestic,INR,D1 Block,Gurugram,Haryana,India,Food
1742,2019-07-07,CAFE COFFEE DAYILD TRADE ...,0.0,Cafe company,-298.0,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
1744,2019-11-07,INDIGOGURGAON ...,0.0,Restaurant company,-200.0,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India,Food

In [50]:
#  Function to find relative bills for each of User in particular category tag

def bill(Name, tag):
    
    ans = (dataset_orig.loc[(dataset_orig['TransactionUserName'] == Name) & (dataset_orig['tags'] == tag)])
    
    
    ans.sort_values(by = ['Date'],inplace = True, ascending = False)
    
    ans.index = range(ans.shape[0])
  
    
    return(ans)

In [51]:
# Food Bill for last Month

Y = bill('       VIBHORE GOYAL','Food')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [52]:
Y

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country,tags
0,2020-12-02,UBER INR MUMBAI ...,0.0,Online food ordering company,-107.68,VIBHORE GOYAL,Domestic,INR,Mumbai,Mumbai,Maharashtra,India,Food
1,2020-11-03,F136 DILKEVENTERSBEHROR ...,0.0,German singer,-177.45,VIBHORE GOYAL,Domestic,INR,Alwar,Behror,Rajasthan,India,Food
2,2020-11-03,CAFE COFFEE DAYALANKAR PL ...,0.0,Cafe company,-140.00,VIBHORE GOYAL,Domestic,INR,Alwar,Behror,Rajasthan,India,Food
3,2020-11-02,UBER INRMUMBAI ...,0.0,Online food ordering company,-388.57,VIBHORE GOYAL,Domestic,INR,Mumbai,Mumbai,Maharashtra,India,Food
4,2020-11-01,SMARTBUYBANGALORE ...,0.0,Coffeehouse company,-6978.00,VIBHORE GOYAL,Domestic,INR,Sector 4,Gurugram,Haryana,India,Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,2019-01-07,CAFE COFFEE DAYNINEX CITY ...,0.0,Cafe company,-272.00,VIBHORE GOYAL,Domestic,INR,Block S,Gurugram,Haryana,India,Food
208,2019-01-07,CAFE COFFEE DAYNINEX CITY ...,0.0,Cafe company,-140.00,VIBHORE GOYAL,Domestic,INR,Block S,Gurugram,Haryana,India,Food
209,2019-01-06,CAFE COFFEE DAY ILD TRADE ...,0.0,Cafe company,-667.00,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
210,2019-01-05,CAFE COFFEE DAY ILD TRADE ...,0.0,Cafe company,-154.00,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Food
211,2019-01-02,KFC SEC 47 SOHNA ROAD GGURGAON ...,0.0,Fast food restaurant company,-265.00,VIBHORE GOYAL,Domestic,INR,D1 Block,Gurugram,Haryana,India,Food

In [53]:
Y['Date'].loc[0].strftime('%m')

'12'

In [54]:
Y['Date'].loc[0].strftime('%y')

'20'

In [55]:
# Function to find latest month bill for each tag corrsponding to each user
# T is a database from above finction

def monthlybill(T):
    a = 0
    i = 0
    while(T['Date'].loc[0].strftime('%m') == T['Date'].loc[i].strftime('%m')):
        a = a + T['Amount'].iloc[i]
        i = i+1
    return(a)

In [56]:
monthlybill(Y)

-107.68

In [57]:
# Monthly travel bill over past n months

X = bill('       VIBHORE GOYAL','Travel')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
X

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country,tags
0,2020-10-01,WWW OLACABS COMGURGAON ...,0.0,Ridesharing company,1.00,VIBHORE GOYAL,Domestic,INR,Dundahera Village,Gurugram,Haryana,India,Travel
1,2020-01-31,INDRPRSTHAGAS BILLDESK MUMBAI ...,0.0,International airline,-2850.62,VIBHORE GOYAL,Domestic,INR,Mumbai,Mumbai,Maharashtra,India,Travel
2,2020-01-28,WWW OLACABS COMGURGAON ...,0.0,Ridesharing company,-150.00,VIBHORE GOYAL,Domestic,INR,Dundahera Village,Gurugram,Haryana,India,Travel
3,2019-12-23,OLACABS.COMGURGAON ...,0.0,Novel by Tamsyn Muir,-2256.00,VIBHORE GOYAL,Domestic,INR,Dundahera Village,Gurugram,Haryana,India,Travel
4,2019-12-18,WWW OLACABS COM GURGAON ...,0.0,Ridesharing company,-1.00,VIBHORE GOYAL,Domestic,INR,Dundahera Village,Gurugram,Haryana,India,Travel
5,2019-12-10,INDIGO GURGAON ...,0.0,Airline,-250.00,VIBHORE GOYAL,Domestic,INR,Sikanderpur,Gurugram,Haryana,India,Travel
6,2019-12-09,IRCTC MPP NEW DELHI ...,0.0,Railway company,-1621.45,VIBHORE GOYAL,Domestic,INR,Sector 31,New Delhi,Delhi,India,Travel
7,2019-11-30,INNER CHEFGURGAON ...,0.0,Airline,-231.00,VIBHORE GOYAL,Domestic,INR,Block B,Gurugram,Haryana,India,Travel
8,2019-11-27,INNER CHEFGURGAON ...,0.0,Airline,-231.00,VIBHORE GOYAL,Domestic,INR,Block B,Gurugram,Haryana,India,Travel
9,2019-09-25,CLEARTRIP PRIVATE LIMIHTTPS://WW ...,0.0,Company,-2357.00,VIBHORE GOYAL,Domestic,INR,Mahim,Mumbai,Maharashtra,India,Travel
10,2019-09-23,IRCTC MPP NEW DELHI ...,0.0,Railway company,-454.90,VIBHORE GOYAL,Domestic,INR,Central Park II,New Delhi,Delhi,India,Travel
11,2019-08-30,IRCTC MPPNEW DELHI ...,0.0,Railway company,-1141.30,VIBHORE GOYAL,Domestic,INR,Sector 42,Gurugram,Delhi,India,Travel
12,2019-07-07,SPICEJET LIMITEDGURGAON ...,0.0,Airline,-1798.00,VIBHORE GOYAL,Domestic,INR,Phase III,Gurugram,Haryana,India,Travel
13,2019-07-02,JET AIRWAYS INDIA LTD MUMBAI ...,0.0,International airline,-2000.00,VIBHORE GOYAL,Domestic,INR,Ashok Nagar,Mumbai,Maharashtra,India,Travel
14,2019-07-02,JET AIRWAYS INDIA LTD MUMBAI ...,0.0,International airline,-1298.00,VIBHORE GOYAL,Domestic,INR,Ashok Nagar,Mumbai,Maharashtra,India,Travel
15,2019-05-25,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-1661.45,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
16,2019-05-15,MECHANDISEEBS MUMBAI ...,0.0,International airline,-2980.00,VIBHORE GOYAL,Domestic,INR,Mumbai,Mumbai,Maharashtra,India,Travel
17,2019-04-25,HTTPS WWW IRCTC CO IN NEW DELHI ...,0.0,Railway company,-1131.20,VIBHORE GOYAL,Domestic,INR,Ber Sarai,New Delhi,Delhi,India,Travel
18,2019-04-23,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,1180.00,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
19,2019-04-22,IRCTC Corp New Delhi ...,0.0,Railway company,-1141.43,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
20,2019-04-21,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-1257.45,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
21,2019-04-06,CLEARTRIP PRIVATE LIMI HTTPS://WW ...,0.0,Company,-11673.00,VIBHORE GOYAL,Domestic,INR,Sohna Road,Gurugram,Haryana,India,Travel
22,2019-02-25,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,850.00,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
23,2019-02-24,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-1598.26,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
24,2019-02-20,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,4190.00,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
25,2019-02-20,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,3523.28,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
26,2019-02-19,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-1852.76,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
27,2019-02-19,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-3523.28,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
28,2019-02-19,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-8129.07,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
29,2019-02-17,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-5964.04,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
30,2019-02-17,INDIAN RAILWAY CATERINGNEW DELHI ...,0.0,Railway company,-5964.04,VIBHORE GOYAL,Domestic,INR,Janpath,New Delhi,Delhi,India,Travel
31,2019-02-13,JET AIRWAYS INDIA LTD MUMBAI ...,0.0,International airline,-2000.00,VIBHORE GOYAL,Domestic,INR,Ashok Nagar,Mumbai,Maharashtra,India,Travel
32,2019-01-19,CLEARTRIP PVT LTD MUMBAI ...,0.0,Company,-1715.00,VIBHORE GOYAL,Domestic,INR,Shastri Nagar,Mumbai,Maharashtra,India,Travel

In [59]:
# Function to find recent n month bills for each user corresponding to each tag

def recentmonthsbill(T,n):
    A = []
    i = 0
    k = 0
    for j in range(n):
        a = 0
        while(T['Date'].loc[k].strftime('%m') == T['Date'].loc[i].strftime('%m')):
           
            a = a + T['Amount'].iloc[i]
            i = i+1
        k = i
        A.append(a)
    return(A)

In [60]:
recentmonthsbill(X,4)

[1.0, -3000.62, -4128.45, -462.0]

In [61]:
# For Impulsive Shopper

Z = bill('       VIBHORE GOYAL','Shopping')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [62]:
# Function to find out purchase frequency for n months for each use corresponding to each tag

def monthpurchasefrequency(T,n):
    A = []
    i = 0
    k = 0
    for j in range(n):
        l = 0
        while(T['Date'].loc[k].strftime('%m') == T['Date'].loc[i].strftime('%m')):
           
            l = l+1
            i = i+1
        k = i
        A.append(l)
    return(A)

In [63]:
Z

,Date,Description,InternationTransaction,Category,Amount,TransactionUserName,TransactionType,IsoCurrency,Locality,City,State,Country,tags
0,2020-11-03,ORIENTAL TRES ALWAR F15BEHROR ...,0.0,Corporation,-37.00,VIBHORE GOYAL,Domestic,INR,Alwar,Alwar,Rajasthan,India,Shopping
1,2020-11-03,PETRO SURCHARGE WAIVER ...,0.0,Corporation,17.00,VIBHORE GOYAL,Domestic,INR,Gurgaon,Gurugram,Haryana,India,Shopping
2,2020-11-02,PAYTMNOIDA ...,0.0,E-commerce company,-1020.00,VIBHORE GOYAL,Domestic,INR,F Block,Noida,Uttar Pradesh,India,Shopping
3,2020-11-01,DesqWorx Smart Hubs Wo Gurgaon ...,0.0,Political party,-15246.00,VIBHORE GOYAL,Domestic,INR,Sector 48,Gurugram,Haryana,India,Shopping
4,2020-10-03,PAYTM APPNOIDA ...,0.0,E-commerce company,-283.00,VIBHORE GOYAL,Domestic,INR,Gautam Buddh Nagar,Noida,Uttar Pradesh,India,Shopping
...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,2019-01-07,PAYTM IVR E COMMERCENOIDA ...,0.0,E-commerce company,-5000.00,VIBHORE GOYAL,Domestic,INR,Gautam Buddh Nagar,Noida,Uttar Pradesh,India,Shopping
337,2019-01-05,S AND S BEAUTY CARE GURGAON ...,0.0,Retail company,-350.00,VIBHORE GOYAL,Domestic,INR,Pocket E,Gurugram,Haryana,India,Shopping
338,2019-01-03,B S FUELSGURGAON ...,0.0,American actress,14.84,VIBHORE GOYAL,Domestic,INR,Dera Mandi,New Delhi,Haryana,India,Shopping
339,2019-01-02,S AND S BEAUTY CAREGURGAON ...,0.0,Retail company,-330.00,VIBHORE GOYAL,Domestic,INR,Mount Vernon,Alexandria,Virginia,United States,Shopping
340,2018-12-27,WWW.ALIBABA.COM LONDONUSD ...,36.0,E-commerce company,2532.86,VIBHORE GOYAL,International,USD,Sector 4,Gurugram,Haryana,India,Shopping

In [64]:
Z.describe()

       InternationTransaction         Amount
count              341.000000     341.000000
mean                 6.928680    8076.763607
std                 39.184897   68014.480015
min                  0.000000 -128450.000000
25%                  0.000000   -5000.000000
50%                  0.000000    -999.000000
75%                  0.000000     -45.150000
max                368.000000  700000.000000

In [65]:
K = monthpurchasefrequency(Z,10)

In [66]:
# K is an array frequency of purchase in each other starting from most recent month
K

[4, 2, 1, 1, 7, 4, 10, 17, 21, 27]

In [67]:
# Function to categorise into Impulsive or Non Impulsive shopper

def impulsiveshopper(K):
    for i in K:
        if(i>10):
            return("Yes")

    return("No")

In [68]:
impulsiveshopper(K)

'Yes'